<?php
/**
 * XSL stylesheet for the XML sitemaps — makes both the index and the sub-sitemaps
 * human-readable in a browser. Served with an application/xslt+xml content type.
 */

declare(strict_types=1);

defined( 'ABSPATH' ) || exit;

// These strings are local to this template partial — the file is required from
// a controller method, so the variables live in that method's scope, not the
// global namespace. They are pre-escaped with esc_html__() here for output below.
// phpcs:disable WordPress.NamingConventions.PrefixAllGlobals.NonPrefixedVariableFound
$fsa_title     = esc_html__( 'XML Sitemap', 'flexa-seo-aeo' );
$fsa_generated = esc_html__( 'Generated by Flexa SEO', 'flexa-seo-aeo' );
$fsa_col_url   = esc_html__( 'URL', 'flexa-seo-aeo' );
$fsa_col_mod   = esc_html__( 'Last modified', 'flexa-seo-aeo' );
$fsa_intro     = esc_html__( 'This XML sitemap is used by search engines and AI answer engines to crawl your site.', 'flexa-seo-aeo' );
// phpcs:enable WordPress.NamingConventions.PrefixAllGlobals.NonPrefixedVariableFound

echo '<?xml version="1.0" encoding="UTF-8"?>' . "\n";
?>
<xsl:stylesheet version="1.0"
	xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
	xmlns:s="http://www.sitemaps.org/schemas/sitemap/0.9">
	<xsl:output method="html" encoding="UTF-8" indent="yes"/>
	<xsl:template match="/">
		<html lang="en">
			<head>
				<title><?php echo $fsa_title; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?></title>
				<meta charset="UTF-8"/>
				<meta name="robots" content="noindex,follow"/>
				<!--
				Inline style is required: this is an XSLT stylesheet served as application/xslt+xml,
				not an enqueue-able HTML page. An XSL transform has no wp_head / wp_enqueue_scripts,
				so the CSS cannot be enqueued. WP core, Yoast and Rank Math inline sitemap CSS the same way.
				-->
				<style>
					body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;color:#1e293b;margin:0;padding:2rem;background:#f8fafc}
					.wrap{max-width:1000px;margin:0 auto}
					h1{font-size:1.5rem;margin:0 0 .25rem}
					.muted{color:#64748b;font-size:.875rem;margin:0 0 1.5rem}
					table{width:100%;border-collapse:collapse;background:#fff;border:1px solid #e2e8f0;border-radius:8px;overflow:hidden}
					th,td{text-align:left;padding:.6rem .9rem;font-size:.875rem;border-bottom:1px solid #f1f5f9}
					th{background:#f1f5f9;font-weight:600}
					tr:last-child td{border-bottom:0}
					a{color:#2563eb;text-decoration:none}
					a:hover{text-decoration:underline}
					.count{font-weight:600}
				</style>
			</head>
			<body>
				<div class="wrap">
					<h1><?php echo $fsa_title; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?></h1>
					<p class="muted"><?php echo $fsa_intro; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?></p>
					<xsl:choose>
						<xsl:when test="s:sitemapindex">
							<p class="muted count"><xsl:value-of select="count(s:sitemapindex/s:sitemap)"/> sitemaps</p>
							<table>
								<tr><th><?php echo $fsa_col_url; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?></th><th><?php echo $fsa_col_mod; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?></th></tr>
								<xsl:for-each select="s:sitemapindex/s:sitemap">
									<tr>
										<td><a href="{s:loc}"><xsl:value-of select="s:loc"/></a></td>
										<td><xsl:value-of select="s:lastmod"/></td>
									</tr>
								</xsl:for-each>
							</table>
						</xsl:when>
						<xsl:otherwise>
							<p class="muted count"><xsl:value-of select="count(s:urlset/s:url)"/> URLs</p>
							<table>
								<tr><th><?php echo $fsa_col_url; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?></th><th><?php echo $fsa_col_mod; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?></th></tr>
								<xsl:for-each select="s:urlset/s:url">
									<tr>
										<td><a href="{s:loc}"><xsl:value-of select="s:loc"/></a></td>
										<td><xsl:value-of select="s:lastmod"/></td>
									</tr>
								</xsl:for-each>
							</table>
						</xsl:otherwise>
					</xsl:choose>
					<p class="muted"><?php echo $fsa_generated; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?></p>
				</div>
			</body>
		</html>
	</xsl:template>
</xsl:stylesheet>
